name: Build and Deploy
env:
  CI: false
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
        env:
          REACT_APP_TOKEN: ${{ secrets.BLOG_APP_TOKEN }}
          REACT_APP_OAUTH_CID: ${{ secrets.BLOG_OAUTH_CID }}
          REACT_APP_OAUTH_SECRET: ${{ secrets.BLOG_OAUTH_SECRET }}
          REACT_APP_BLOG_REPO: ${{ secrets.BLOG_REPO }}
          REACT_APP_BLOG_TITLE: ${{ secrets.BLOG_TITLE }}
          REACT_APP_BLOG_USER: ${{ secrets.BLOG_USER }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4.1.8
        with:
          ACCESS_TOKEN: ${{ secrets.BLOG_SECRET_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
